---
parent: 'test_cases/test_branch_jenkins_images.yml'
overrides:
  email:
    - abenaiss@redhat.com
    - vbobade@redhat.com
    - shbose@redhat.com
    - olemefer@redhat.com
    - openshift-dev-services+jenkins@redhat.com
extensions:
  actions:
    - type: "script"
      title: "create directory for docker config"
      script: |-
        mkdir -p /tmp/.docker
        chmod a+rwx /tmp/.docker
    - type: "host_script"
      title: "Copy docker credentials to instance"
      timeout: 60
      script: |-
        scp -F ${WORKSPACE}/.config/origin-ci-tool/inventory/.ssh_config /var/lib/jenkins/.docker/config.json openshiftdevel:/tmp/.docker/
    - type: "script"
      title: "push the jenkins images"
      repository: "jenkins"
      timeout: 7200
      script: |-
        sudo chmod a+rw /tmp/.docker/config.json
        export DOCKER_CONFIG=/tmp/.docker

        version_tag=$(cat release.version)

        docker tag docker.io/openshift/jenkins-2-centos7 docker.io/openshift/jenkins-2-centos7:${version_tag}
        docker push docker.io/openshift/jenkins-2-centos7:${version_tag}

        docker tag docker.io/openshift/jenkins-slave-base-centos7 docker.io/openshift/jenkins-slave-base-centos7:${version_tag}
        docker push docker.io/openshift/jenkins-slave-base-centos7:${version_tag}

        if [[ $version_tag == v3* ]];
        then
           docker tag docker.io/openshift/jenkins-slave-maven-centos7 docker.io/openshift/jenkins-slave-maven-centos7:${version_tag}
           docker push docker.io/openshift/jenkins-slave-maven-centos7:${version_tag}

           docker tag docker.io/openshift/jenkins-slave-nodejs-centos7 docker.io/openshift/jenkins-slave-nodejs-centos7:${version_tag}
           docker push docker.io/openshift/jenkins-slave-nodejs-centos7:${version_tag}
        fi

        docker tag docker.io/openshift/jenkins-agent-maven-35-centos7 docker.io/openshift/jenkins-agent-maven-35-centos7:${version_tag}
        docker push docker.io/openshift/jenkins-agent-maven-35-centos7:${version_tag}

        docker tag docker.io/openshift/jenkins-agent-nodejs-8-centos7 docker.io/openshift/jenkins-agent-nodejs-8-centos7:${version_tag}
        docker push docker.io/openshift/jenkins-agent-nodejs-8-centos7:${version_tag}

        # only push to latest if we're building the master branch.
        if [ "${PULL_BASE_REF}" = "master" ]; then
          docker push docker.io/openshift/jenkins-2-centos7

          docker push docker.io/openshift/jenkins-slave-base-centos7

          docker push docker.io/openshift/jenkins-agent-maven-35-centos7

          docker push docker.io/openshift/jenkins-agent-nodejs-8-centos7
        fi
