---
parent: 'common/test_cases/origin_release_with_ecosystem.yml'
overrides:
  junit_analysis: False
  email:
    - aos-apiserver@redhat.com
  sync:
    - "openshift,origin=master"
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        OPENSHIFT_SKIP_BUILD='true' JUNIT_REPORT='true' make test-extended SUITE=ldap_groups
