---
parent: 'common/test_cases/origin_built_release.yml'
extensions:
  actions:
    - type: "script"
      title: "pull image for oc binary"
      repository: "origin"
      script: |-
        sudo docker pull openshift/origin-cli:v3.11
        sudo docker create --name temp-container openshift/origin-cli:v3.11
        sudo docker cp temp-container:/usr/bin/oc ./
        sudo docker rm temp-container
        sudo mv -f ./oc /bin/oc
    - type: "script"
      title: "start openshift server"
      repository: "origin"
      script: |-
        oc version
        oc cluster up --public-hostname=localhost --loglevel=5 --server-loglevel=5
    - type: "script"
      title: "run web console tests"
      repository: "origin-web-console"
      script: |-
        # Chrome Version 76.0.3809.0 (Developer Build) (64-bit)
        # https://omahaproxy.appspot.com/
        BRANCH_BASE="665006"
        BRANCH_SHA256SUM="a1ae2e0950828f991119825f62c24464ab3765aa219d150a94fb782a4c66a744"
        CHROME_DIR="/tmp/__chrome_browser__"
        CHROME_DOWNLOAD_URL="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots"

        # download
        mkdir -p "${CHROME_DIR}/${BRANCH_BASE}"
        curl -G "${CHROME_DOWNLOAD_URL}/o/Linux_x64%2F${BRANCH_BASE}%2Fchrome-linux.zip" \
            -d "alt=media" \
            > "${CHROME_DIR}/chrome-linux-${BRANCH_BASE}.zip"
        unzip "${CHROME_DIR}/chrome-linux-${BRANCH_BASE}.zip" -d "${CHROME_DIR}/${BRANCH_BASE}"

        # check sha256sum
        if [ "$(sha256sum ${CHROME_DIR}/chrome-linux-${BRANCH_BASE}.zip | cut -f 1 -d ' ')" != "${BRANCH_SHA256SUM}" ];
        then
          echo "ERROR: chrmoe binary sha256 missmatch"
          exit 1
        fi

        export CHROME_BIN="${CHROME_DIR}/${BRANCH_BASE}/chrome-linux/chrome"
        export PATH=$PATH:$(pwd)/node_modules/.bin
        make test
  post_actions:
    - type: "script"
      title: "grab container logs"
      repository: "origin"
      script: |-
        trap 'exit 0' EXIT
        ( source hack/lib/init.sh; os::cleanup::dump_container_logs )
  artifacts:
    - "/data/src/github.com/openshift/origin-web-console/test/tmp/screenshots/"
    - "/data/src/github.com/openshift/origin-web-console/test/coverage/"
    - "/data/src/github.com/openshift/origin-web-console/test/junit/"
    - "/data/src/github.com/openshift/origin-web-console/test/reports/"
